//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brandlist_Export_Assistant.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Brandlist_Export_Assistant.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AfghanistanAFG
        ///AlandIslandsALA
        ///AlbaniaALB
        ///AlgeriaDZA
        ///AmericanSamoaASM
        ///AndorraAND
        ///AngolaAGO
        ///AnguillaAIA
        ///AntarcticaATA
        ///AntiguaandBarbudaATG
        ///ArgentinaARG
        ///ArmeniaARM
        ///ArubaABW
        ///AustraliaAUS
        ///AustriaAUT
        ///AzerbaijanAZE
        ///BahamasBHS
        ///BahrainBHR
        ///BangladeshBGD
        ///BarbadosBRB
        ///BelarusBLR
        ///BelgiumBEL
        ///BelizeBLZ
        ///BeninBEN
        ///BermudaBMU
        ///BhutanBTN
        ///BoliviaBOL
        ///BonaireSintEustatiusandSabaBES
        ///BosniaandHerzegovinaBIH
        ///BotswanaBWA
        ///BouvetIslandBVT
        ///BrazilBRA
        ///BritishIndianOceanTerritoryIOT
        ///BruneiDarussalamBRN
        ///Bulg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AC]$Acholi
        ///[AF]$Afrikaans
        ///[AF-ZA]$Afrikaans (South Africa)
        ///[AK]$Akan
        ///[AM]$Amharic
        ///[AM-ET]$Amharic (Ethiopia)
        ///[AR]$Arabic
        ///[AR-AE]$Arabic - United Arab Emirates
        ///[AR-BH]$Arabic - Bahrain
        ///[AR-DZ]$Arabic - Algeria
        ///[AR-EG]$Arabic - Egypt
        ///[AR-IQ]$Arabic - Iraq
        ///[AR-JO]$Arabic - Jordan
        ///[AR-KW]$Arabic - Kuwait
        ///[AR-LB]$Arabic - Lebanon
        ///[AR-LY]$Arabic - Libya
        ///[AR-MA]$Arabic - Morocco
        ///[AR-OM]$Arabic - Oman
        ///[AR-QA]$Arabic - Qatar
        ///[AR-SA]$Arabic - Saudi Arabia
        ///[AR-SY]$Arabic - Syria
        ///[AR-TN]$Arabic -  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Countries_iField {
            get {
                return ResourceManager.GetString("Countries_iField", resourceCulture);
            }
        }
    }
}
